# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.11

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/cdoug/gitroot/photoeditor

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/cdoug/gitroot/photoeditor

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cdoug/gitroot/photoeditor/CMakeFiles /home/cdoug/gitroot/photoeditor/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cdoug/gitroot/photoeditor/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named format_chunky.run

# Build rule for target.
format_chunky.run: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 format_chunky.run
.PHONY : format_chunky.run

# fast build rule for target.
format_chunky.run/fast:
	$(MAKE) -f CMakeFiles/format_chunky.run.dir/build.make CMakeFiles/format_chunky.run.dir/build
.PHONY : format_chunky.run/fast

#=============================================================================
# Target rules for targets named format_chunky.rungen

# Build rule for target.
format_chunky.rungen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 format_chunky.rungen
.PHONY : format_chunky.rungen

# fast build rule for target.
format_chunky.rungen/fast:
	$(MAKE) -f CMakeFiles/format_chunky.rungen.dir/build.make CMakeFiles/format_chunky.rungen.dir/build
.PHONY : format_chunky.rungen/fast

#=============================================================================
# Target rules for targets named format_chunky_cc_gen

# Build rule for target.
format_chunky_cc_gen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 format_chunky_cc_gen
.PHONY : format_chunky_cc_gen

# fast build rule for target.
format_chunky_cc_gen/fast:
	$(MAKE) -f CMakeFiles/format_chunky_cc_gen.dir/build.make CMakeFiles/format_chunky_cc_gen.dir/build
.PHONY : format_chunky_cc_gen/fast

#=============================================================================
# Target rules for targets named format_chunky_lib_gen

# Build rule for target.
format_chunky_lib_gen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 format_chunky_lib_gen
.PHONY : format_chunky_lib_gen

# fast build rule for target.
format_chunky_lib_gen/fast:
	$(MAKE) -f CMakeFiles/format_chunky_lib_gen.dir/build.make CMakeFiles/format_chunky_lib_gen.dir/build
.PHONY : format_chunky_lib_gen/fast

#=============================================================================
# Target rules for targets named format_chunky_cc

# Build rule for target.
format_chunky_cc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 format_chunky_cc
.PHONY : format_chunky_cc

# fast build rule for target.
format_chunky_cc/fast:
	$(MAKE) -f CMakeFiles/format_chunky_cc.dir/build.make CMakeFiles/format_chunky_cc.dir/build
.PHONY : format_chunky_cc/fast

#=============================================================================
# Target rules for targets named format_chunky.generator_binary

# Build rule for target.
format_chunky.generator_binary: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 format_chunky.generator_binary
.PHONY : format_chunky.generator_binary

# fast build rule for target.
format_chunky.generator_binary/fast:
	$(MAKE) -f CMakeFiles/format_chunky.generator_binary.dir/build.make CMakeFiles/format_chunky.generator_binary.dir/build
.PHONY : format_chunky.generator_binary/fast

#=============================================================================
# Target rules for targets named _halide_library_from_generator_rungen

# Build rule for target.
_halide_library_from_generator_rungen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 _halide_library_from_generator_rungen
.PHONY : _halide_library_from_generator_rungen

# fast build rule for target.
_halide_library_from_generator_rungen/fast:
	$(MAKE) -f CMakeFiles/_halide_library_from_generator_rungen.dir/build.make CMakeFiles/_halide_library_from_generator_rungen.dir/build
.PHONY : _halide_library_from_generator_rungen/fast

#=============================================================================
# Target rules for targets named halide_rt_host_runtime_gen

# Build rule for target.
halide_rt_host_runtime_gen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 halide_rt_host_runtime_gen
.PHONY : halide_rt_host_runtime_gen

# fast build rule for target.
halide_rt_host_runtime_gen/fast:
	$(MAKE) -f CMakeFiles/halide_rt_host_runtime_gen.dir/build.make CMakeFiles/halide_rt_host_runtime_gen.dir/build
.PHONY : halide_rt_host_runtime_gen/fast

#=============================================================================
# Target rules for targets named halide_library_runtime.generator_stub_gen

# Build rule for target.
halide_library_runtime.generator_stub_gen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 halide_library_runtime.generator_stub_gen
.PHONY : halide_library_runtime.generator_stub_gen

# fast build rule for target.
halide_library_runtime.generator_stub_gen/fast:
	$(MAKE) -f CMakeFiles/halide_library_runtime.generator_stub_gen.dir/build.make CMakeFiles/halide_library_runtime.generator_stub_gen.dir/build
.PHONY : halide_library_runtime.generator_stub_gen/fast

#=============================================================================
# Target rules for targets named format_chunky.generator_library

# Build rule for target.
format_chunky.generator_library: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 format_chunky.generator_library
.PHONY : format_chunky.generator_library

# fast build rule for target.
format_chunky.generator_library/fast:
	$(MAKE) -f CMakeFiles/format_chunky.generator_library.dir/build.make CMakeFiles/format_chunky.generator_library.dir/build
.PHONY : format_chunky.generator_library/fast

#=============================================================================
# Target rules for targets named format_chunky.generator_stub_gen

# Build rule for target.
format_chunky.generator_stub_gen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 format_chunky.generator_stub_gen
.PHONY : format_chunky.generator_stub_gen

# fast build rule for target.
format_chunky.generator_stub_gen/fast:
	$(MAKE) -f CMakeFiles/format_chunky.generator_stub_gen.dir/build.make CMakeFiles/format_chunky.generator_stub_gen.dir/build
.PHONY : format_chunky.generator_stub_gen/fast

#=============================================================================
# Target rules for targets named halide_library_runtime.generator_binary

# Build rule for target.
halide_library_runtime.generator_binary: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 halide_library_runtime.generator_binary
.PHONY : halide_library_runtime.generator_binary

# fast build rule for target.
halide_library_runtime.generator_binary/fast:
	$(MAKE) -f CMakeFiles/halide_library_runtime.generator_binary.dir/build.make CMakeFiles/halide_library_runtime.generator_binary.dir/build
.PHONY : halide_library_runtime.generator_binary/fast

genfiles/format_chunky/format_chunky.generated.o: genfiles/format_chunky/format_chunky.generated.cpp.o

.PHONY : genfiles/format_chunky/format_chunky.generated.o

# target to build an object file
genfiles/format_chunky/format_chunky.generated.cpp.o:
	$(MAKE) -f CMakeFiles/format_chunky_cc.dir/build.make CMakeFiles/format_chunky_cc.dir/genfiles/format_chunky/format_chunky.generated.cpp.o
.PHONY : genfiles/format_chunky/format_chunky.generated.cpp.o

genfiles/format_chunky/format_chunky.generated.i: genfiles/format_chunky/format_chunky.generated.cpp.i

.PHONY : genfiles/format_chunky/format_chunky.generated.i

# target to preprocess a source file
genfiles/format_chunky/format_chunky.generated.cpp.i:
	$(MAKE) -f CMakeFiles/format_chunky_cc.dir/build.make CMakeFiles/format_chunky_cc.dir/genfiles/format_chunky/format_chunky.generated.cpp.i
.PHONY : genfiles/format_chunky/format_chunky.generated.cpp.i

genfiles/format_chunky/format_chunky.generated.s: genfiles/format_chunky/format_chunky.generated.cpp.s

.PHONY : genfiles/format_chunky/format_chunky.generated.s

# target to generate assembly for a file
genfiles/format_chunky/format_chunky.generated.cpp.s:
	$(MAKE) -f CMakeFiles/format_chunky_cc.dir/build.make CMakeFiles/format_chunky_cc.dir/genfiles/format_chunky/format_chunky.generated.cpp.s
.PHONY : genfiles/format_chunky/format_chunky.generated.cpp.s

home/cdoug/ext/halide/tools/GenGen.o: home/cdoug/ext/halide/tools/GenGen.cpp.o

.PHONY : home/cdoug/ext/halide/tools/GenGen.o

# target to build an object file
home/cdoug/ext/halide/tools/GenGen.cpp.o:
	$(MAKE) -f CMakeFiles/format_chunky.generator_binary.dir/build.make CMakeFiles/format_chunky.generator_binary.dir/home/cdoug/ext/halide/tools/GenGen.cpp.o
	$(MAKE) -f CMakeFiles/halide_library_runtime.generator_binary.dir/build.make CMakeFiles/halide_library_runtime.generator_binary.dir/home/cdoug/ext/halide/tools/GenGen.cpp.o
.PHONY : home/cdoug/ext/halide/tools/GenGen.cpp.o

home/cdoug/ext/halide/tools/GenGen.i: home/cdoug/ext/halide/tools/GenGen.cpp.i

.PHONY : home/cdoug/ext/halide/tools/GenGen.i

# target to preprocess a source file
home/cdoug/ext/halide/tools/GenGen.cpp.i:
	$(MAKE) -f CMakeFiles/format_chunky.generator_binary.dir/build.make CMakeFiles/format_chunky.generator_binary.dir/home/cdoug/ext/halide/tools/GenGen.cpp.i
	$(MAKE) -f CMakeFiles/halide_library_runtime.generator_binary.dir/build.make CMakeFiles/halide_library_runtime.generator_binary.dir/home/cdoug/ext/halide/tools/GenGen.cpp.i
.PHONY : home/cdoug/ext/halide/tools/GenGen.cpp.i

home/cdoug/ext/halide/tools/GenGen.s: home/cdoug/ext/halide/tools/GenGen.cpp.s

.PHONY : home/cdoug/ext/halide/tools/GenGen.s

# target to generate assembly for a file
home/cdoug/ext/halide/tools/GenGen.cpp.s:
	$(MAKE) -f CMakeFiles/format_chunky.generator_binary.dir/build.make CMakeFiles/format_chunky.generator_binary.dir/home/cdoug/ext/halide/tools/GenGen.cpp.s
	$(MAKE) -f CMakeFiles/halide_library_runtime.generator_binary.dir/build.make CMakeFiles/halide_library_runtime.generator_binary.dir/home/cdoug/ext/halide/tools/GenGen.cpp.s
.PHONY : home/cdoug/ext/halide/tools/GenGen.cpp.s

home/cdoug/ext/halide/tools/RunGen.o: home/cdoug/ext/halide/tools/RunGen.cpp.o

.PHONY : home/cdoug/ext/halide/tools/RunGen.o

# target to build an object file
home/cdoug/ext/halide/tools/RunGen.cpp.o:
	$(MAKE) -f CMakeFiles/_halide_library_from_generator_rungen.dir/build.make CMakeFiles/_halide_library_from_generator_rungen.dir/home/cdoug/ext/halide/tools/RunGen.cpp.o
.PHONY : home/cdoug/ext/halide/tools/RunGen.cpp.o

home/cdoug/ext/halide/tools/RunGen.i: home/cdoug/ext/halide/tools/RunGen.cpp.i

.PHONY : home/cdoug/ext/halide/tools/RunGen.i

# target to preprocess a source file
home/cdoug/ext/halide/tools/RunGen.cpp.i:
	$(MAKE) -f CMakeFiles/_halide_library_from_generator_rungen.dir/build.make CMakeFiles/_halide_library_from_generator_rungen.dir/home/cdoug/ext/halide/tools/RunGen.cpp.i
.PHONY : home/cdoug/ext/halide/tools/RunGen.cpp.i

home/cdoug/ext/halide/tools/RunGen.s: home/cdoug/ext/halide/tools/RunGen.cpp.s

.PHONY : home/cdoug/ext/halide/tools/RunGen.s

# target to generate assembly for a file
home/cdoug/ext/halide/tools/RunGen.cpp.s:
	$(MAKE) -f CMakeFiles/_halide_library_from_generator_rungen.dir/build.make CMakeFiles/_halide_library_from_generator_rungen.dir/home/cdoug/ext/halide/tools/RunGen.cpp.s
.PHONY : home/cdoug/ext/halide/tools/RunGen.cpp.s

home/cdoug/ext/halide/tools/RunGenStubs.o: home/cdoug/ext/halide/tools/RunGenStubs.cpp.o

.PHONY : home/cdoug/ext/halide/tools/RunGenStubs.o

# target to build an object file
home/cdoug/ext/halide/tools/RunGenStubs.cpp.o:
	$(MAKE) -f CMakeFiles/format_chunky.rungen.dir/build.make CMakeFiles/format_chunky.rungen.dir/home/cdoug/ext/halide/tools/RunGenStubs.cpp.o
.PHONY : home/cdoug/ext/halide/tools/RunGenStubs.cpp.o

home/cdoug/ext/halide/tools/RunGenStubs.i: home/cdoug/ext/halide/tools/RunGenStubs.cpp.i

.PHONY : home/cdoug/ext/halide/tools/RunGenStubs.i

# target to preprocess a source file
home/cdoug/ext/halide/tools/RunGenStubs.cpp.i:
	$(MAKE) -f CMakeFiles/format_chunky.rungen.dir/build.make CMakeFiles/format_chunky.rungen.dir/home/cdoug/ext/halide/tools/RunGenStubs.cpp.i
.PHONY : home/cdoug/ext/halide/tools/RunGenStubs.cpp.i

home/cdoug/ext/halide/tools/RunGenStubs.s: home/cdoug/ext/halide/tools/RunGenStubs.cpp.s

.PHONY : home/cdoug/ext/halide/tools/RunGenStubs.s

# target to generate assembly for a file
home/cdoug/ext/halide/tools/RunGenStubs.cpp.s:
	$(MAKE) -f CMakeFiles/format_chunky.rungen.dir/build.make CMakeFiles/format_chunky.rungen.dir/home/cdoug/ext/halide/tools/RunGenStubs.cpp.s
.PHONY : home/cdoug/ext/halide/tools/RunGenStubs.cpp.s

src/editor/main.o: src/editor/main.cc.o

.PHONY : src/editor/main.o

# target to build an object file
src/editor/main.cc.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/editor/main.cc.o
.PHONY : src/editor/main.cc.o

src/editor/main.i: src/editor/main.cc.i

.PHONY : src/editor/main.i

# target to preprocess a source file
src/editor/main.cc.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/editor/main.cc.i
.PHONY : src/editor/main.cc.i

src/editor/main.s: src/editor/main.cc.s

.PHONY : src/editor/main.s

# target to generate assembly for a file
src/editor/main.cc.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/editor/main.cc.s
.PHONY : src/editor/main.cc.s

src/generators/format_chunky.o: src/generators/format_chunky.cc.o

.PHONY : src/generators/format_chunky.o

# target to build an object file
src/generators/format_chunky.cc.o:
	$(MAKE) -f CMakeFiles/format_chunky.generator_library.dir/build.make CMakeFiles/format_chunky.generator_library.dir/src/generators/format_chunky.cc.o
.PHONY : src/generators/format_chunky.cc.o

src/generators/format_chunky.i: src/generators/format_chunky.cc.i

.PHONY : src/generators/format_chunky.i

# target to preprocess a source file
src/generators/format_chunky.cc.i:
	$(MAKE) -f CMakeFiles/format_chunky.generator_library.dir/build.make CMakeFiles/format_chunky.generator_library.dir/src/generators/format_chunky.cc.i
.PHONY : src/generators/format_chunky.cc.i

src/generators/format_chunky.s: src/generators/format_chunky.cc.s

.PHONY : src/generators/format_chunky.s

# target to generate assembly for a file
src/generators/format_chunky.cc.s:
	$(MAKE) -f CMakeFiles/format_chunky.generator_library.dir/build.make CMakeFiles/format_chunky.generator_library.dir/src/generators/format_chunky.cc.s
.PHONY : src/generators/format_chunky.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... main"
	@echo "... format_chunky.run"
	@echo "... format_chunky.rungen"
	@echo "... format_chunky_cc_gen"
	@echo "... format_chunky_lib_gen"
	@echo "... edit_cache"
	@echo "... format_chunky_cc"
	@echo "... format_chunky.generator_binary"
	@echo "... _halide_library_from_generator_rungen"
	@echo "... halide_rt_host_runtime_gen"
	@echo "... halide_library_runtime.generator_stub_gen"
	@echo "... format_chunky.generator_library"
	@echo "... rebuild_cache"
	@echo "... format_chunky.generator_stub_gen"
	@echo "... halide_library_runtime.generator_binary"
	@echo "... genfiles/format_chunky/format_chunky.generated.o"
	@echo "... genfiles/format_chunky/format_chunky.generated.i"
	@echo "... genfiles/format_chunky/format_chunky.generated.s"
	@echo "... home/cdoug/ext/halide/tools/GenGen.o"
	@echo "... home/cdoug/ext/halide/tools/GenGen.i"
	@echo "... home/cdoug/ext/halide/tools/GenGen.s"
	@echo "... home/cdoug/ext/halide/tools/RunGen.o"
	@echo "... home/cdoug/ext/halide/tools/RunGen.i"
	@echo "... home/cdoug/ext/halide/tools/RunGen.s"
	@echo "... home/cdoug/ext/halide/tools/RunGenStubs.o"
	@echo "... home/cdoug/ext/halide/tools/RunGenStubs.i"
	@echo "... home/cdoug/ext/halide/tools/RunGenStubs.s"
	@echo "... src/editor/main.o"
	@echo "... src/editor/main.i"
	@echo "... src/editor/main.s"
	@echo "... src/generators/format_chunky.o"
	@echo "... src/generators/format_chunky.i"
	@echo "... src/generators/format_chunky.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

