load("@halide//:halide.bzl", "halide_library")

halide_library(
 	name = "format_chunky",
 	srcs = ["format_chunky.cc"],
	halide_target_map = {
		"x86-64-linux": ["x86-64-linux"],
	},
 	visibility = ["//editor:__pkg__"],
)
